# Docker Compose para desenvolvimento
version: "3.8"

services:
  # Backend Python FastAPI
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379/0
      - API_HOST=0.0.0.0
      - API_PORT=8000
    volumes:
      - .:/app
      - /app/__pycache__
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - zaplify-network

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zaplify-network

  # Nginx (opcional para produção)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - zaplify-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  zaplify-network:
    driver: bridge
