FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm i
COPY tsconfig.json ./
COPY src ./src
ENV NODE_ENV=production
RUN npm run build
EXPOSE 8080
CMD ["node","dist/index.js"]
