// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcswnrndfpmtxpyiknsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc3ducm5kZnBtdHhweWlrbnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNTc2MzcsImV4cCI6MjA2NzkzMzYzN30.EMZoLh0u2PW6YK8rICz5awhL0rtU4f1U8PrV0nTbl3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
