[tool.ruff]
line-length = 100
target-version = "py312"
extend-select = ["I"] # organize imports

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["app"]
