version: "3.9"

name: zaplify-ai-flow-dev
services:
  api-gateway:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /app
    env_file:
      - ../services/api-gateway/.env
    ports:
      - "8080:8080"
    volumes:
      - ../services/api-gateway/src:/app/src
      - ../services/api-gateway/package.json:/app/package.json
      - ../services/api-gateway/tsconfig.json:/app/tsconfig.json
    networks: [zapnet]

  whatsapp-service:
    build:
      context: ../services/whatsapp-service
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /app
    env_file:
      - ../services/whatsapp-service/.env
    ports:
      - "8081:8081"
    volumes:
      - ../services/whatsapp-service/src:/app/src
      - ../services/whatsapp-service/package.json:/app/package.json
      - ../services/whatsapp-service/tsconfig.json:/app/tsconfig.json
    networks: [zapnet]

  funnel-engine:
    build:
      context: ../services/funnel-engine
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /app
    env_file:
      - ../services/funnel-engine/.env
    ports:
      - "8082:8082"
    volumes:
      - ../services/funnel-engine/src:/app/src
      - ../services/funnel-engine/package.json:/app/package.json
      - ../services/funnel-engine/tsconfig.json:/app/tsconfig.json
    networks: [zapnet]

  ia-conversational:
    build:
      context: ../services/ia-conversational
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    working_dir: /app
    env_file:
      - ../services/ia-conversational/.env
    ports:
      - "8001:8001"
    volumes:
      - ../services/ia-conversational/app:/app/app
    networks: [zapnet]

  analytics-service:
    build:
      context: ../services/analytics-service
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    working_dir: /app
    env_file:
      - ../services/analytics-service/.env
    ports:
      - "8002:8002"
    volumes:
      - ../services/analytics-service/app:/app/app
    networks: [zapnet]

networks:
  zapnet:
    driver: bridge
