openapi: 3.0.3
info:
  title: WhatsApp Service API
  description: Microserviço para integração com WhatsApp via Evolution API
  version: 1.0.0
  contact:
    name: WhatsApp Service Team
    email: tech@company.com

servers:
  - url: http://localhost:8081
    description: Desenvolvimento

paths:
  /health/health:
    get:
      summary: Health Check
      description: Verifica status de saúde do serviço
      tags:
        - Health
      responses:
        '200':
          description: Serviço funcionando
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  service:
                    type: string
                    example: whatsapp-service
                  timestamp:
                    type: string
                    format: date-time

  /health/status:
    get:
      summary: Status Detalhado
      description: Status do serviço e dependências
      tags:
        - Health
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/TenantId'
      responses:
        '200':
          description: Status detalhado
          content:
            application/json:
              schema:
                type: object
                properties:
                  service:
                    type: string
                  evolution:
                    type: object
                    properties:
                      status:
                        type: string
                  timestamp:
                    type: string
                    format: date-time

  /api/v1/send:
    post:
      summary: Enviar Mensagem
      description: Envia mensagem de texto ou mídia via WhatsApp
      tags:
        - Messages
      parameters:
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/TenantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  description: Número do destinatário
                  example: '5511999999999'
                text:
                  type: string
                  description: Texto da mensagem
                  example: 'Olá, como vai?'
                media:
                  type: object
                  description: Mídia para envio
                  properties:
                    type:
                      type: string
                      enum: [image, video, audio, document]
                    url:
                      type: string
                      format: uri
                    caption:
                      type: string
              required:
                - to
              oneOf:
                - required: [text]
                - required: [media]
      responses:
        '200':
          description: Mensagem enviada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendMessageResponse'
        '400':
          description: Dados inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '429':
          description: Rate limit excedido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitError'
        '500':
          description: Erro interno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /webhook/messages:
    post:
      summary: Webhook de Mensagens
      description: Recebe webhooks da Evolution API
      tags:
        - Webhooks
      parameters:
        - name: x-signature
          in: header
          required: true
          schema:
            type: string
          description: Assinatura HMAC SHA256
        - $ref: '#/components/parameters/CorrelationId'
        - $ref: '#/components/parameters/TenantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookPayload'
      responses:
        '200':
          description: Webhook processado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: processed
                  messageId:
                    type: string
        '401':
          description: Assinatura inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Payload inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'

components:
  parameters:
    CorrelationId:
      name: x-correlation-id
      in: header
      required: false
      schema:
        type: string
        format: uuid
      description: ID de correlação para rastreamento

    TenantId:
      name: x-tenant-id
      in: header
      required: false
      schema:
        type: string
      description: ID do tenant para multi-tenancy

  schemas:
    SendMessageResponse:
      type: object
      properties:
        messageId:
          type: string
          description: ID da mensagem
        status:
          type: string
          enum: [sent, delivered, failed]
        timestamp:
          type: number
          description: Timestamp Unix

    WebhookPayload:
      type: object
      properties:
        event:
          type: string
        instance:
          type: string
        data:
          type: object
          properties:
            key:
              type: object
              properties:
                id:
                  type: string
                remoteJid:
                  type: string
                fromMe:
                  type: boolean
            message:
              type: object
            messageTimestamp:
              type: number

    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: 'Validation failed'
        details:
          type: array
          items:
            type: object

    RateLimitError:
      type: object
      properties:
        error:
          type: string
          example: 'Too Many Requests'
        retryAfter:
          type: number
          description: Segundos para tentar novamente

    Error:
      type: object
      properties:
        error:
          type: string
          description: Mensagem de erro

  securitySchemes:
    HmacSignature:
      type: apiKey
      in: header
      name: x-signature
      description: Assinatura HMAC SHA256 para webhooks

tags:
  - name: Health
    description: Endpoints de saúde do serviço
  - name: Messages
    description: Envio de mensagens
  - name: Webhooks
    description: Recebimento de webhooks
